const colors = {
  light: {
    text: "#0f172a",
    tint: "#00b4d8",
    background: "#f8fafc",
    foreground: "#0f172a",
    card: "#ffffff",
    cardForeground: "#0f172a",
    primary: "#00b4d8",
    primaryForeground: "#ffffff",
    secondary: "#e2e8f0",
    secondaryForeground: "#475569",
    muted: "#f1f5f9",
    mutedForeground: "#64748b",
    accent: "#7c3aed",
    accentForeground: "#ffffff",
    destructive: "#ef4444",
    destructiveForeground: "#ffffff",
    border: "#e2e8f0",
    input: "#ffffff",
    success: "#22c55e",
    warning: "#f59e0b",
    cyan: "#00b4d8",
    purple: "#7c3aed",
    pink: "#ec4899",
    orange: "#f97316",
    green: "#22c55e",
  },
  dark: {
    text: "#e0e8ff",
    tint: "#00d4ff",
    background: "#060b18",
    foreground: "#e0e8ff",
    card: "#0d1a2e",
    cardForeground: "#e0e8ff",
    primary: "#00d4ff",
    primaryForeground: "#060b18",
    secondary: "#0f2440",
    secondaryForeground: "#a0b4cc",
    muted: "#0f2440",
    mutedForeground: "#6a8aaa",
    accent: "#7c3aed",
    accentForeground: "#ffffff",
    destructive: "#ff3b6b",
    destructiveForeground: "#ffffff",
    border: "#1a2f4a",
    input: "#0d1a2e",
    success: "#00ff9d",
    warning: "#ffb800",
    cyan: "#00d4ff",
    purple: "#7c3aed",
    pink: "#ff006e",
    orange: "#ff6b00",
    green: "#00ff9d",
  },
  radius: 12,
  // Accent color palette — single source of truth for the accent swatches.
  // Hex values here match the themeStore accent swatches exactly.
  accents: {
    cyan: "#00d4ff",
    purple: "#7c3aed",
    pink: "#ff006e",
    green: "#00ff9d",
    orange: "#ff6b00",
  },
};

export default colors;