import js from '@eslint/js';
import tseslint from 'typescript-eslint';
import reactNative from 'eslint-plugin-react-native';
import reactHooks from 'eslint-plugin-react-hooks';
import importPlugin from 'eslint-plugin-import';

export default [
  {
    ignores: [
      '**/*.js',
      '**/*.json',
      '**/node_modules/**',
      '**/dist/**',
      '**/build/**',
      '**/coverage/**',
      '**/scripts/**',
      '**/server/**',
      // Agent Manager worktrees hold full copies of the repo; linting them
      // duplicates results and surfaces errors from unrelated branches.
      '.kilo/worktrees/**',
      'static-build/**',
      // Expo regenerates these route types on every `expo start`, so linting
      // them reports on machine-generated code we do not own.
      '.expo/**',
      // Auto-generated by `metro.config.js` from the stories glob. Regenerated
      // on every Metro run, so it is not code we own and should not be linted.
      '.storybook/storybook.requires.ts',
      'metro.config.js',
      'babel.config.js',
      'jest.config.js',
    ],
  },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  {
    files: ['**/*.{ts,tsx}'],
    plugins: {
      'react-hooks': reactHooks,
      'react-native': reactNative,
      'import': importPlugin,
    },
    rules: {
      'prefer-const': 'error',
      'no-unused-vars': 'off', // Turn off for TS files, use TypeScript version
      'react-hooks/rules-of-hooks': 'error',
      'react-hooks/exhaustive-deps': 'warn',
      'import/order': ['warn', { 'newlines-between': 'always' }],
      'no-console': 'off', // Allow console in development
      'no-debugger': 'error',
      '@typescript-eslint/no-unused-vars': ['warn', { argsIgnorePattern: '^_' }],
      '@typescript-eslint/no-explicit-any': 'off', // Allow any for flexibility
      'react-native/no-unused-styles': 'warn',
      'react-native/split-platform-components': 'warn',
      'react-native/no-inline-styles': 'off',
      'react-native/no-color-literals': 'off',
      '@typescript-eslint/no-shadow': ['error'],
      'no-shadow': 'off',
      'no-undef': 'off', // TypeScript handles this
      '@typescript-eslint/no-require-imports': 'off', // Allow require in some cases
    },
    settings: {
      'import/resolver': {
        typescript: {
          alwaysTryTypes: true,
        },
      },
    },
  },
];
